### ISSUE TITLE
Reveal direction

### ISSUE THREAD

**Issue by carlos-dubon** [remorses/baby-i-am-faded#5]
Is there a way to tell the lib a direction from which elements should apear?

**Comment by remorses** [comment]
you can use a custom animation like this one to appear elements from above instead of below
```css
@keyframes babyFadeInUp {
    from {
        opacity: 0;
        transform: translate3d(0px, -2em, 0px);
    }
    to {
        transform: none;
    }
}
```
You then have to pass the aniamtion name to animation
